import streamlit as st

from prompt import generate_prompts
from llm import get_response


# Page configuration
st.set_page_config(
    page_title="AI Prompt Explorer",
    page_icon="✨",
    layout="wide"
)


# Application title
st.title("✨ AI Prompt Explorer")
st.write(
    "Explore how different prompting styles can change the response "
    "generated by a Large Language Model."
)


# Topic input
topic = st.text_input(
    "Enter a topic",
    placeholder="Example: Machine Learning"
)


# Generate button
if st.button("🚀 Explore Prompts"):

    if not topic.strip():
        st.warning("Please enter a topic before continuing.")

    else:
        # Generate different prompts
        prompts = generate_prompts(topic)

        st.subheader("📝 Generated Prompts")

        # Display prompts in columns
        col1, col2, col3 = st.columns(3)

        with col1:
            st.markdown("### Simple Prompt")
            st.code(prompts["Simple Prompt"])

        with col2:
            st.markdown("### Expert Prompt")
            st.code(prompts["Expert Prompt"])

        with col3:
            st.markdown("### Q&A Prompt")
            st.code(prompts["Q&A Prompt"])

        st.divider()

        # Generate LLM responses
        st.subheader("🤖 AI Responses")

        for prompt_name, prompt_text in prompts.items():

            st.markdown(f"### {prompt_name}")

            with st.spinner(
                f"Generating {prompt_name} response..."
            ):
                response = get_response(prompt_text)

            st.write(response)

            st.divider()